environment:
  matrix:
    - LWS_METHOD: default

    - LWS_METHOD: noserver
      CMAKE_ARGS: -DLWS_WITHOUT_SERVER=ON

    - LWS_METHOD: noclient
      CMAKE_ARGS: -DLWS_WITHOUT_CLIENT=ON

    - LWS_METHOD: noext
      CMAKE_ARGS: -DLWS_WITHOUT_EXTENSIONS=ON

    - LWS_METHOD: nossl
      CMAKE_ARGS: -DLWS_WITH_SSL=OFF
install:
  - appveyor DownloadFile http://slproweb.com/download/Win32OpenSSL-1_0_2.exe
  - Win32OpenSSL-1_0_2.exe /silent /verysilent /sp- /suppressmsgboxes
  - cinst nsis
build:

build_script:
  - md build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release %CMAKE_ARGS% ..
  - cmake --build . --config Release

after_build:
  - cd ..
  - cd win32port
  - C:\Program Files\NSIS\makensis.exe -DVERSION=%APPVEYOR_BUILD_VERSION% libwebsockets.nsi'


artifacts:
  - name: Installer
    path: 'win32port/libwebsockets-*-install.exe'

cache:
  - C:\OpenSSL-Win32

